version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    ports:
      - 9200:9200
    volumes:
      - ${PWD}/dev/elastic-config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml